online_class/assignment/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

# urlpatterns = [
#     path('',assignment_home, name='assignment_page'),
#     path('add/',assignment_add, name='assignment_add'),
# ]


urlpatterns = [
    path('', home, name='home'),
    
    path('teachers/', include(([
        path('', assignment_home, name='assignment_page'),
        path('assignment/add/', assignment_add, name='assignment_add'),
        path('assignment/<int:pk>/', assignment_update, name='assignment_update'),
        path('assignment/<int:pk>/delete/', assignment_delete, name='assignment_delete'),
        path('assignment/<int:pk>/submitted/', submitted_assignment, name='assignment_submitted'),
    ],'assignment'), namespace='teachers')),

    path('students/', include(([
        path('', student_assignment_home, name='assignment_page'),
        path('<int:pk>/submit', student_assignment_upload, name='assignment_upload'),
    ],'assignment'), namespace='students'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

online_class/exam/urls.py
from django.urls import path, include
from .views import (
    exam_view,
    exam_home,
    exam_add,
    exam_update,
    exam_delete,
    exam_answer_list,
    exam_answer_check,

    student_exam_home,
    exam_submit,
)

urlpatterns = [
    path('', exam_view, name="exam_page"),

    path('teachers/', exam_home, name='exam_page_details_teacher'),
    path('teachers/add/', exam_add, name='exam_add'),
    path('teachers/update/<int:pk>/', exam_update, name='exam_update'),
    path('teachers/<int:pk>/delete/', exam_delete, name='exam_delete'),
    path('teachers/<int:pk>/answers/', exam_answer_list, name='exam_answer_list'),
    path('teachers/<int:pk>/answers/check/', exam_answer_check, name='exam_answer_check'),

    path('students/', student_exam_home, name='exam_page_details_student'),
    path('students/submit/<int:pk>/', exam_submit, name='exam_submit')
]

online_class/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="index"),
    path('index/', views.main_view, name="main_page"),
]

online_class/online_class/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('main.urls')),
    path('class/', include('class.urls')),
    path('exam/', include('exam.urls')),
    path('assignment/', include('assignment.urls')),
    path('profile/', include('user_profile.urls')),
    path('face-recognition/', include('faceDetector.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

online_class/main/models.py
from django.db import models

online_class/main/views.py
from django.shortcuts import render, redirect



def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:assignment_page')
        else:
            return redirect('main_page')
    return redirect('login')



def main_view(request):
    context = {

    }

    return render(request, 'main.html', context)

online_class/templates/main/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- bootstrap stylesheet and material icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/material_icons.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% comment %} <script type="text/javascript" src="https://unpkg.com/webcam-easy/dist/webcam-easy.min.js"></script> {% endcomment %}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/webcamjs/1.0.25/webcam.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>


    {% block links %}
    {% endblock links %}

    <style>
        body{
            overflow-x: hidden;
            color: #fff;
        }
    </style>

    <title>
        {% block title %}
        {% endblock title %}
    </title>
</head>

<body style="background: #222831">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'main_page' %}">
            <span class="material-icons" style="position: absolute;transform: translate(-10%, 20%);">
                laptop_chromebook
            </span>
            <span class="ml-4">
                Online Classroom
            </span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main_page' %}">
                        <span class="material-icons" style="position: absolute;">
                            home
                        </span>
                        <span class="ml-4">
                            Home
                        </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'class_page' %}">
                        <span class="material-icons" style="position: absolute;">
                            school
                        </span>
                        <span class="ml-4">
                            Classes
                        </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'exam_page' %}">
                        <span class="material-icons" style="position: absolute;">
                            menu_book
                        </span>
                        <span class="ml-4">
                            Exams
                        </span>
                    </a>
                </li>
                <li class="nav-item">
                {% if user.is_teacher %}
                    <a class="nav-link" href="{% url 'teachers:assignment_page' %}">
                {% else %}
                    <a class="nav-link" href="{% url 'students:assignment_page' %}">
                {% endif %}
                        <span class="material-icons" style="position: absolute;">
                            assignment
                        </span>
                        <span class="ml-4">
                            Assignments
                        </span>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
                        <span class="material-icons" style="position: absolute;">
                            account_circle
                        </span>
                        <span class="ml-4">
                            Sijan Joshi
                        </span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'profile_page' %}">
                        <span class="material-icons" style="position: absolute;">
                            person
                        </span>
                        <span class="ml-4">
                            My Profile
                        </span>
                      </a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'logout' %}">
                        <span class="material-icons" style="position: absolute;">
                            close
                        </span>
                        <span class="ml-4">
                            Sign out
                        </span>
                      </a>
                    </div>
                  </li>
            </ul>
        </div>
    </nav>

    {% block body %}
    {% endblock body %}

    <footer class="bg-dark text-light w-100">
        <div class="container p-4">
            <div class="row">
                <div class="col-xs-12 col-md-4">
                    <div>
                        General
                    </div>
                    <hr>
                    <a class="small text-warning" href="{% url 'main_page' %}">Home</a><br>
                    <a class="small text-warning" href="{% url 'class_page' %}">Classes</a><br>
                    <a class="small text-warning" href="{% url 'exam_page' %}">Exams</a><br>
                    <a class="small text-warning" href="{% url 'teachers:assignment_page' %}">Assignment</a>
                </div>
                <div class="col-xs-12 col-md-4">
                    <div>
                        About
                    </div>
                    <hr>
                    <a class="small text-warning" href="">Telegram</a><br>
                    <a class="small text-warning" href="">Discord</a><br>
                    <a class="small text-warning" href="">About us</a>
                </div>
                <div class="col-xs-12 col-md-4">
                    <div>
                        Help & Support
                    </div>
                    <hr>
                    <a class="small text-warning" href="">Terms & Condition</a><br>
                    <a class="small text-warning" href="">Privacy Policy</a><br>
                    <a class="small text-warning" href="">Help and Support</a><br>
                    <a class="small text-warning" href="">Contact us</a>
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-center small pt-2 pb-3">
            2020 Online Classroom
        </div>
    </footer>

    <!-- bootstrap scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    {% block scripts %}
    {% endblock scripts %}
</body>

</html>