online_class/assignment/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

# urlpatterns = [
#     path('',assignment_home, name='assignment_page'),
#     path('add/',assignment_add, name='assignment_add'),
# ]


urlpatterns = [
    path('', home, name='home'),
    
    path('teachers/', include(([
        path('', assignment_home, name='assignment_page'),
        path('assignment/add/', assignment_add, name='assignment_add'),
        path('assignment/<int:pk>/', assignment_update, name='assignment_update'),
        path('assignment/<int:pk>/delete/', assignment_delete, name='assignment_delete'),
        path('assignment/<int:pk>/submitted/', submitted_assignment, name='assignment_submitted'),
    ],'assignment'), namespace='teachers')),

    path('students/', include(([
        path('', student_assignment_home, name='assignment_page'),
        path('<int:pk>/submit', student_assignment_upload, name='assignment_upload'),
    ],'assignment'), namespace='students'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

online_class/exam/urls.py
from django.urls import path, include
from .views import (
    exam_view,
    exam_home,
    exam_add,
    exam_update,
    exam_delete,
    exam_answer_list,
    exam_answer_check,

    student_exam_home,
    exam_submit,
)

urlpatterns = [
    path('', exam_view, name="exam_page"),

    path('teachers/', exam_home, name='exam_page_details_teacher'),
    path('teachers/add/', exam_add, name='exam_add'),
    path('teachers/update/<int:pk>/', exam_update, name='exam_update'),
    path('teachers/<int:pk>/delete/', exam_delete, name='exam_delete'),
    path('teachers/<int:pk>/answers/', exam_answer_list, name='exam_answer_list'),
    path('teachers/<int:pk>/answers/check/', exam_answer_check, name='exam_answer_check'),

    path('students/', student_exam_home, name='exam_page_details_student'),
    path('students/submit/<int:pk>/', exam_submit, name='exam_submit')
]

online_class/online_class/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('main.urls')),
    path('class/', include('class.urls')),
    path('exam/', include('exam.urls')),
    path('assignment/', include('assignment.urls')),
    path('profile/', include('user_profile.urls')),
    path('face-recognition/', include('faceDetector.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

online_class/assignment/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import date


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    email = models.EmailField(max_length=100)


# class Subject(models.Model):
#     name = models.CharField(max_length=30)
#     level = models.CharField(max_length=30, null=False)

#     def __str__(self):
#         return self.name
    

class Assignment(models.Model):

    def user_directory_path(instance, filename):
        return 'user_{0}/{1}'.format(instance.owner.id, filename)

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=225)
    subject = models.ForeignKey('class.Class', on_delete=models.CASCADE)
    submission_date = models.DateField("Submission Date")
    date_added = models.DateField(auto_now_add=True)
    question = models.FileField(upload_to=user_directory_path)

    def __str__(self):
        return self.title


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    roll_no = models.PositiveIntegerField(unique=True, null=False)
    sem = models.PositiveIntegerField(verbose_name="Semister", default=5)

    def __str__(self):
        return self.user.username
    

class StudentAnswer(models.Model):

    def user_directory_path(instance, filename):
        return 'user_{0}/{1}'.format(instance.student.id, filename)
        
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='assignment_answers')
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    question = models.FileField(upload_to=user_directory_path)
    submitted_date = models.DateField(auto_now_add=True, null= True)


class AnswerRemark(models.Model):
    Remarks = models.TextField('Remarks', default="No remarks added!", null=True)
    studentanswer = models.ForeignKey(StudentAnswer, on_delete=models.CASCADE)

    def __str__(self):
        return self.Remarks

online_class/assignment/forms.py
from django import forms
from . import models


class AssignmentAddForm(forms.ModelForm):
    class Meta:
        model = models.Assignment
        fields = ['title', 'subject', 'submission_date', 'question']


class AssignmentSubmitForm(forms.ModelForm):
    class Meta:
        model = models.StudentAnswer
        fields = ['question']

online_class/assignment/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator

from .forms import *
from .decorators import *
from .models import *


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:assignment_page')
        else:
            return redirect('students:assignment_page')
    return redirect('login')


#<------teachers-view---------->

@login_required
@teacher_required
def assignment_home(request):
    assignments = Assignment.objects.filter(owner_id = request.user.id)
    num = int(0)
    context = {
        'assignments' : assignments,
        'num' : num
    }

    return render(request, 'teachers/assignment_home.html', context)


@login_required
@teacher_required
def assignment_add(request):
    if request.method == 'POST':
        form = AssignmentAddForm(request.POST, request.FILES)
        if form.is_valid():
            assignment = form.save(commit=False)
            assignment.owner = request.user
            assignment.save()
            return redirect('teachers:assignment_page')
    else:
        form = AssignmentAddForm()
    
    return render(request, 'teachers/assignment_add.html', {'form':form})


@login_required
@teacher_required
def assignment_update(request, pk):
    assignment = Assignment.objects.get(pk=pk)
    if request.method == 'POST':
        form = AssignmentAddForm(request.POST, request.FILES)
        if form.is_valid():
            assignment = form.save(commit=False)
            assignment.owner = request.user
            assignment.save()
            return redirect('assignment_page')
    else:
        form = AssignmentAddForm(instance=assignment)
    
    return render(request, 'teachers/assignment_update.html', {'form':form, 'assignment':assignment})


@login_required
@teacher_required
def assignment_delete(request,pk):
    assignment = Assignment.objects.get(pk=pk)
    assignment.delete()

    return redirect('teachers:assignment_page')


@login_required
@teacher_required
def submitted_assignment(request,pk):
    answers = StudentAnswer.objects.filter(assignment__id = pk)
    context ={
        'answers': answers,
    }
    
    return render(request, 'teachers/submitted_assignment.html', context)


#<-----------Students-view----------->

@login_required
@student_required
def student_assignment_home(request):
    sem = request.user.student.sem

    assignments = Assignment.objects.filter(subject__sem = sem)
    num = int(0)
    context = {
        'assignments' : assignments,
        'num' : num
    }

    return render(request, 'students/assignment_home.html', context)


@login_required
@student_required
def student_assignment_upload(request, pk):
    assignment = Assignment.objects.get(pk = pk)
    if request.method == 'POST':
        form = AssignmentSubmitForm(request.POST, request.FILES)
        if form.is_valid():
            studentanswer = form.save(commit=False)
            studentanswer.student = request.user.student
            studentanswer.assignment = assignment
            studentanswer.save()
            return redirect('students:assignment_page')
    else:
        form = AssignmentSubmitForm()
    
    return render(request, 'students/assignment_upload.html', {'form':form})
        

online_class/assignment/templates/students/assignment_home.html
{% extends 'main/base.html' %}

{% block title %}
Assignments
{% endblock title %}

{% block body %}

<div class="container py-4">
    <div>
        <h2>
            Assignments
        </h2>
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-3">
                <form action="#" method="GET">
                    <div class="input-group input-group-sm mb-3">
                        <div class="input-group-prepend">
                          <label class="input-group-text" for="assignment_sort">sort</label>
                        </div>
                        <select class="custom-select custom-select-sm" id="assignment_sort" name="assignment_sort">
                          <option selected>Choose...</option>
                          <option value="assignment_sort_date">Date</option>
                          <option value="assignment_sort_subject">subject</option>
                        </select>
                      </div>
                </form>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-dark table-striped table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Subject</th>
                    <th>Due Date</th>
                    <th>Time Remaining</th>
                    <th>Assignment</th>
                </tr>
            </thead>
            <tbody>
                {% for assignment in assignments %}
                    <tr>
                        <th>{{ forloop.counter }}</th>
                        <td>{{ assignment.subject }}</td>
                        <td>{{ assignment.submission_date }}</td>
                        <td>Today</td>
                        <td>
                            <a href="{{ assignment.question.url }}" class="btn btn-sm btn-secondary" style="position: relative; width: 100px;"> 
                                <span class="material-icons md-18" style="position: absolute;top: 50%;transform: translate(0, -50%);">
                                    get_app
                                </span> 
                                <span class="pl-4">
                                    Download
                                </span>
                            </a>
                            <a href="{% url 'students:assignment_upload' assignment.pk %}" class="btn btn-sm btn-secondary" style="position: relative; width: 100px;"> 
                                <span class="material-icons md-18" style="position: absolute;top: 50%;transform: translate(0, -50%);">
                                    publish
                                </span> 
                                <span class="pl-4">
                                    Upload
                                </span>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock body %}

online_class/assignment/templates/students/assignment_upload.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
Assignment - Submit
{% endblock title %}

{% block body %}
    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock body %}